support reading/writing the internal flash
hydrausb3/hydrausb3_fw pull request #3
Opened 2022-08-02 03:04 UTC by hansfbaier

Hi, 
this is translated straight from my Forth implementation.
I also added multiword support for flash writes.
Multiword support for reads still would need to be done.
I didn't compile/test yet, so you might want to test it.

2022-08-02 15:42 UTC, bvernoux commented on SRC/Peripheral/inc/CH56x_flash.h
> +UINT8  FLASH_ROMA_ReadByte ( UINT32 addr );
Could you replace the ugly UNIT8/UINT32 and so one by more standard (from stdint.h) uint8_t/uint32_t ?

2022-08-02 21:57 UTC, bvernoux requested changes

2022-08-02 22:25 UTC, hansfbaier commented on SRC/Peripheral/src/CH56x_flash.c
> +static void FLASH_ROMA_Access(UINT8 access_code)
Really? All the other header and .c files use the types from CH56xSFR.h

2022-08-03 11:39 UTC, bvernoux commented on SRC/Peripheral/src/CH56x_flash.c
> +static void FLASH_ROMA_Access(UINT8 access_code)
I have planned a full refactor of all *.h (even those not modifed so far) to remove the ugly UINT8 ... and to replace by the standard stdint.h uint8_t ...
So the aim so far is just to fix the code you push to use the correct type from stdint.h uint8_t ...

2022-08-05 06:22 UTC, hansfbaier commented
I think this is ready now. Tested working:
```
Boot
00s 000ms 000us Start
00s 001ms 993us HSPI_Tx 2022/07/30 @ChipID=69
00s 006ms 068us FSYS=120000000
00s 008ms 841us 
before erase: 

    5000:  343ee2b8 142ea2b8 f43ea2b8 d42e62b8 b43e62b8 942e22b8 743f22b8 542fe2b8
    5020:  343fe2b9 142fa2b9 f43fa2b9 d42f62b9 b43f62b9 942f22b9 743c22b9 542ce2b9
    5040:  343ce2ba 142ca2ba f43ca2ba d42c62ba b43c62ba 942c22ba 743d22ba 542de2ba
    5060:  343de2bb 142da2bb f43da2bb d42d62bb b43d62bb 942d22bb 743a22bb 542ae2bb
    5080:  343ae2bc 142aa2bc f43aa2bc d42a62bc b43a62bc 942a22bc 743b22bc 542be2bc
    50a0:  343be2bd 142ba2bd f43ba2bd d42b62bd b43b62bd 942b22bd 743822bd 5428e2bd
    50c0:  3438e2be 1428a2be f438a2be d42862be b43862be 942822be 743922be 5429e2be
    50e0:  3439e2bf 1429a2bf f439a2bf d42962bf b43962bf 9f2922bf ffff22bf ffffffbf
    5100:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5120:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5140:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5160:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5180:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    51a0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    51c0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    51e0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5200:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5220:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5240:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5260:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5280:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    52a0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    52c0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    52e0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5300:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5320:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5340:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5360:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5380:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    53a0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    53c0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    53e0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5400:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5420:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5440:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5460:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5480:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    54a0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    54c0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    54e0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5500:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5520:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5540:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5560:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5580:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    55a0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    55c0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    55e0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5600:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5620:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5640:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5660:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5680:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    56a0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    56c0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    56e0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5700:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5720:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5740:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5760:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5780:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    57a0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    57c0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    57e0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffffAddr:     5000 
Addr:     5000 rom_addr:     d000
succ 0
erase success:  0
00s 484ms 553us 
after erase: 

    5000:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5020:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5040:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5060:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5080:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    50a0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    50c0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    50e0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5100:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5120:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5140:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5160:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5180:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    51a0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    51c0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    51e0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5200:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5220:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5240:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5260:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5280:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    52a0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    52c0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    52e0:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5300:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5320:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5340:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5360:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
    5380:  ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff  [...]

2022-08-05 16:13 UTC, bvernoux approved these changes

2022-08-05 16:14 UTC, bvernoux approved these changes

2022-08-05 16:14 UTC, merged

2022-08-05 16:14 UTC, bvernoux commented
Thanks for your contribution !!